# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'menu-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Adjust to 'localhost:8080' if not using Docker Desktop